/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AccessLogService } from "../accessLog.service";
import { AccessLogCreateInput } from "./AccessLogCreateInput";
import { AccessLog } from "./AccessLog";
import { AccessLogFindManyArgs } from "./AccessLogFindManyArgs";
import { AccessLogWhereUniqueInput } from "./AccessLogWhereUniqueInput";
import { AccessLogUpdateInput } from "./AccessLogUpdateInput";
import { LinkFindManyArgs } from "../../link/base/LinkFindManyArgs";
import { Link } from "../../link/base/Link";
import { LinkWhereUniqueInput } from "../../link/base/LinkWhereUniqueInput";

export class AccessLogControllerBase {
  constructor(protected readonly service: AccessLogService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AccessLog })
  async createAccessLog(
    @common.Body() data: AccessLogCreateInput
  ): Promise<AccessLog> {
    return await this.service.createAccessLog({
      data: {
        ...data,

        link: data.link
          ? {
              connect: data.link,
            }
          : undefined,
      },
      select: {
        browserName: true,
        browserVersion: true,
        createdAt: true,
        id: true,

        link: {
          select: {
            id: true,
          },
        },

        osName: true,
        osVersion: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AccessLog] })
  @ApiNestedQuery(AccessLogFindManyArgs)
  async accessLogs(@common.Req() request: Request): Promise<AccessLog[]> {
    const args = plainToClass(AccessLogFindManyArgs, request.query);
    return this.service.accessLogs({
      ...args,
      select: {
        browserName: true,
        browserVersion: true,
        createdAt: true,
        id: true,

        link: {
          select: {
            id: true,
          },
        },

        osName: true,
        osVersion: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AccessLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async accessLog(
    @common.Param() params: AccessLogWhereUniqueInput
  ): Promise<AccessLog | null> {
    const result = await this.service.accessLog({
      where: params,
      select: {
        browserName: true,
        browserVersion: true,
        createdAt: true,
        id: true,

        link: {
          select: {
            id: true,
          },
        },

        osName: true,
        osVersion: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AccessLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAccessLog(
    @common.Param() params: AccessLogWhereUniqueInput,
    @common.Body() data: AccessLogUpdateInput
  ): Promise<AccessLog | null> {
    try {
      return await this.service.updateAccessLog({
        where: params,
        data: {
          ...data,

          link: data.link
            ? {
                connect: data.link,
              }
            : undefined,
        },
        select: {
          browserName: true,
          browserVersion: true,
          createdAt: true,
          id: true,

          link: {
            select: {
              id: true,
            },
          },

          osName: true,
          osVersion: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AccessLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAccessLog(
    @common.Param() params: AccessLogWhereUniqueInput
  ): Promise<AccessLog | null> {
    try {
      return await this.service.deleteAccessLog({
        where: params,
        select: {
          browserName: true,
          browserVersion: true,
          createdAt: true,
          id: true,

          link: {
            select: {
              id: true,
            },
          },

          osName: true,
          osVersion: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/links")
  @ApiNestedQuery(LinkFindManyArgs)
  async findLinks(
    @common.Req() request: Request,
    @common.Param() params: AccessLogWhereUniqueInput
  ): Promise<Link[]> {
    const query = plainToClass(LinkFindManyArgs, request.query);
    const results = await this.service.findLinks(params.id, {
      ...query,
      select: {
        accessLog: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expirationDate: true,
        id: true,
        originalUrl: true,
        shortCode: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/links")
  async connectLinks(
    @common.Param() params: AccessLogWhereUniqueInput,
    @common.Body() body: LinkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      links: {
        connect: body,
      },
    };
    await this.service.updateAccessLog({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/links")
  async updateLinks(
    @common.Param() params: AccessLogWhereUniqueInput,
    @common.Body() body: LinkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      links: {
        set: body,
      },
    };
    await this.service.updateAccessLog({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/links")
  async disconnectLinks(
    @common.Param() params: AccessLogWhereUniqueInput,
    @common.Body() body: LinkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      links: {
        disconnect: body,
      },
    };
    await this.service.updateAccessLog({
      where: params,
      data,
      select: { id: true },
    });
  }
}
