/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccessLogWhereUniqueInput } from "../../accessLog/base/AccessLogWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { AccessLogListRelationFilter } from "../../accessLog/base/AccessLogListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { MetricListRelationFilter } from "../../metric/base/MetricListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";

@InputType()
class LinkWhereInput {
  @ApiProperty({
    required: false,
    type: () => AccessLogWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccessLogWhereUniqueInput)
  @IsOptional()
  @Field(() => AccessLogWhereUniqueInput, {
    nullable: true,
  })
  accessLog?: AccessLogWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AccessLogListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AccessLogListRelationFilter)
  @IsOptional()
  @Field(() => AccessLogListRelationFilter, {
    nullable: true,
  })
  accessLogs?: AccessLogListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  expirationDate?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MetricListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MetricListRelationFilter)
  @IsOptional()
  @Field(() => MetricListRelationFilter, {
    nullable: true,
  })
  metrics?: MetricListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  originalUrl?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  shortCode?: StringNullableFilter;
}

export { LinkWhereInput as LinkWhereInput };
