/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LinkService } from "../link.service";
import { LinkCreateInput } from "./LinkCreateInput";
import { Link } from "./Link";
import { LinkFindManyArgs } from "./LinkFindManyArgs";
import { LinkWhereUniqueInput } from "./LinkWhereUniqueInput";
import { LinkUpdateInput } from "./LinkUpdateInput";
import { AccessLogFindManyArgs } from "../../accessLog/base/AccessLogFindManyArgs";
import { AccessLog } from "../../accessLog/base/AccessLog";
import { AccessLogWhereUniqueInput } from "../../accessLog/base/AccessLogWhereUniqueInput";
import { MetricFindManyArgs } from "../../metric/base/MetricFindManyArgs";
import { Metric } from "../../metric/base/Metric";
import { MetricWhereUniqueInput } from "../../metric/base/MetricWhereUniqueInput";

export class LinkControllerBase {
  constructor(protected readonly service: LinkService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Link })
  async createLink(@common.Body() data: LinkCreateInput): Promise<Link> {
    return await this.service.createLink({
      data: {
        ...data,

        accessLog: data.accessLog
          ? {
              connect: data.accessLog,
            }
          : undefined,
      },
      select: {
        accessLog: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expirationDate: true,
        id: true,
        originalUrl: true,
        shortCode: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Link] })
  @ApiNestedQuery(LinkFindManyArgs)
  async links(@common.Req() request: Request): Promise<Link[]> {
    const args = plainToClass(LinkFindManyArgs, request.query);
    return this.service.links({
      ...args,
      select: {
        accessLog: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expirationDate: true,
        id: true,
        originalUrl: true,
        shortCode: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Link })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async link(
    @common.Param() params: LinkWhereUniqueInput
  ): Promise<Link | null> {
    const result = await this.service.link({
      where: params,
      select: {
        accessLog: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expirationDate: true,
        id: true,
        originalUrl: true,
        shortCode: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Link })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLink(
    @common.Param() params: LinkWhereUniqueInput,
    @common.Body() data: LinkUpdateInput
  ): Promise<Link | null> {
    try {
      return await this.service.updateLink({
        where: params,
        data: {
          ...data,

          accessLog: data.accessLog
            ? {
                connect: data.accessLog,
              }
            : undefined,
        },
        select: {
          accessLog: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          expirationDate: true,
          id: true,
          originalUrl: true,
          shortCode: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Link })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLink(
    @common.Param() params: LinkWhereUniqueInput
  ): Promise<Link | null> {
    try {
      return await this.service.deleteLink({
        where: params,
        select: {
          accessLog: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          expirationDate: true,
          id: true,
          originalUrl: true,
          shortCode: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/accessLogs")
  @ApiNestedQuery(AccessLogFindManyArgs)
  async findAccessLogs(
    @common.Req() request: Request,
    @common.Param() params: LinkWhereUniqueInput
  ): Promise<AccessLog[]> {
    const query = plainToClass(AccessLogFindManyArgs, request.query);
    const results = await this.service.findAccessLogs(params.id, {
      ...query,
      select: {
        browserName: true,
        browserVersion: true,
        createdAt: true,
        id: true,

        link: {
          select: {
            id: true,
          },
        },

        osName: true,
        osVersion: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/accessLogs")
  async connectAccessLogs(
    @common.Param() params: LinkWhereUniqueInput,
    @common.Body() body: AccessLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accessLogs: {
        connect: body,
      },
    };
    await this.service.updateLink({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/accessLogs")
  async updateAccessLogs(
    @common.Param() params: LinkWhereUniqueInput,
    @common.Body() body: AccessLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accessLogs: {
        set: body,
      },
    };
    await this.service.updateLink({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/accessLogs")
  async disconnectAccessLogs(
    @common.Param() params: LinkWhereUniqueInput,
    @common.Body() body: AccessLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accessLogs: {
        disconnect: body,
      },
    };
    await this.service.updateLink({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/metrics")
  @ApiNestedQuery(MetricFindManyArgs)
  async findMetrics(
    @common.Req() request: Request,
    @common.Param() params: LinkWhereUniqueInput
  ): Promise<Metric[]> {
    const query = plainToClass(MetricFindManyArgs, request.query);
    const results = await this.service.findMetrics(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        link: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        totalAccesses: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/metrics")
  async connectMetrics(
    @common.Param() params: LinkWhereUniqueInput,
    @common.Body() body: MetricWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      metrics: {
        connect: body,
      },
    };
    await this.service.updateLink({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/metrics")
  async updateMetrics(
    @common.Param() params: LinkWhereUniqueInput,
    @common.Body() body: MetricWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      metrics: {
        set: body,
      },
    };
    await this.service.updateLink({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/metrics")
  async disconnectMetrics(
    @common.Param() params: LinkWhereUniqueInput,
    @common.Body() body: MetricWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      metrics: {
        disconnect: body,
      },
    };
    await this.service.updateLink({
      where: params,
      data,
      select: { id: true },
    });
  }
}
