/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccessLogWhereUniqueInput } from "../../accessLog/base/AccessLogWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { AccessLogUpdateManyWithoutLinksInput } from "./AccessLogUpdateManyWithoutLinksInput";
import { MetricUpdateManyWithoutLinksInput } from "./MetricUpdateManyWithoutLinksInput";

@InputType()
class LinkUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AccessLogWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccessLogWhereUniqueInput)
  @IsOptional()
  @Field(() => AccessLogWhereUniqueInput, {
    nullable: true,
  })
  accessLog?: AccessLogWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => AccessLogUpdateManyWithoutLinksInput,
  })
  @ValidateNested()
  @Type(() => AccessLogUpdateManyWithoutLinksInput)
  @IsOptional()
  @Field(() => AccessLogUpdateManyWithoutLinksInput, {
    nullable: true,
  })
  accessLogs?: AccessLogUpdateManyWithoutLinksInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  expirationDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => MetricUpdateManyWithoutLinksInput,
  })
  @ValidateNested()
  @Type(() => MetricUpdateManyWithoutLinksInput)
  @IsOptional()
  @Field(() => MetricUpdateManyWithoutLinksInput, {
    nullable: true,
  })
  metrics?: MetricUpdateManyWithoutLinksInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  originalUrl?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  shortCode?: string | null;
}

export { LinkUpdateInput as LinkUpdateInput };
