/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Link } from "./Link";
import { LinkCountArgs } from "./LinkCountArgs";
import { LinkFindManyArgs } from "./LinkFindManyArgs";
import { LinkFindUniqueArgs } from "./LinkFindUniqueArgs";
import { CreateLinkArgs } from "./CreateLinkArgs";
import { UpdateLinkArgs } from "./UpdateLinkArgs";
import { DeleteLinkArgs } from "./DeleteLinkArgs";
import { AccessLogFindManyArgs } from "../../accessLog/base/AccessLogFindManyArgs";
import { AccessLog } from "../../accessLog/base/AccessLog";
import { MetricFindManyArgs } from "../../metric/base/MetricFindManyArgs";
import { Metric } from "../../metric/base/Metric";
import { LinkService } from "../link.service";
@graphql.Resolver(() => Link)
export class LinkResolverBase {
  constructor(protected readonly service: LinkService) {}

  async _linksMeta(
    @graphql.Args() args: LinkCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Link])
  async links(@graphql.Args() args: LinkFindManyArgs): Promise<Link[]> {
    return this.service.links(args);
  }

  @graphql.Query(() => Link, { nullable: true })
  async link(@graphql.Args() args: LinkFindUniqueArgs): Promise<Link | null> {
    const result = await this.service.link(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Link)
  async createLink(@graphql.Args() args: CreateLinkArgs): Promise<Link> {
    return await this.service.createLink({
      ...args,
      data: {
        ...args.data,

        accessLog: args.data.accessLog
          ? {
              connect: args.data.accessLog,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Link)
  async updateLink(@graphql.Args() args: UpdateLinkArgs): Promise<Link | null> {
    try {
      return await this.service.updateLink({
        ...args,
        data: {
          ...args.data,

          accessLog: args.data.accessLog
            ? {
                connect: args.data.accessLog,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Link)
  async deleteLink(@graphql.Args() args: DeleteLinkArgs): Promise<Link | null> {
    try {
      return await this.service.deleteLink(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [AccessLog], { name: "accessLogs" })
  async findAccessLogs(
    @graphql.Parent() parent: Link,
    @graphql.Args() args: AccessLogFindManyArgs
  ): Promise<AccessLog[]> {
    const results = await this.service.findAccessLogs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Metric], { name: "metrics" })
  async findMetrics(
    @graphql.Parent() parent: Link,
    @graphql.Args() args: MetricFindManyArgs
  ): Promise<Metric[]> {
    const results = await this.service.findMetrics(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => AccessLog, {
    nullable: true,
    name: "accessLog",
  })
  async getAccessLog(
    @graphql.Parent() parent: Link
  ): Promise<AccessLog | null> {
    const result = await this.service.getAccessLog(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
